# Generated by Django 4.0.3 on 2022-03-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0006_alter_video_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtuber',
            name='last_upload',
            field=models.DateField(null=True),
        ),
    ]
