# Generated by Django 4.0.3 on 2022-03-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0009_alter_youtuber_last_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='length',
            field=models.TimeField(null=True),
        ),
    ]
